### ISSUE TITLE
Vulnerability disclosure

### ISSUE THREAD

**Issue by Adar-Checkmarx** [ozum/eslint-fixer#1]
Hello,
My name is Adar and I’m a security analyst at Checkmarx's CxSCA group.
I recently found a vulnerability in eslint-fixer.
I couldn’t reach any relevant maintainer to disclose this issue to, and I would appreciate you referring me to the right contact.

Please fell free to reach me at ScaAppSec@checkmarx.com.

Thank you

**Comment by ozum** [comment]
Hi, this library is deprecated.
